services:
  database:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: hollybike
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  minio:
    image: 'minio/minio:RELEASE.2025-04-22T22-12-26Z'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_DEFAULT_BUCKETS=hollybike
      - MINIO_CONSOLE_ADDRESS=:9001
      - BUCKET_NAME=hollybike
    entrypoint: sh
    command: -c 'mkdir -p /data/hollybike && /usr/bin/minio server /data'
volumes:
  db: